/** @format */

const AboutPageType = {
  FETCHING_ABOUT_DATA_START: "FETCHING_ABOUT_DATA_START",
  FETCHING_ABOUT_DATA_SUCCESS: "FETCHING_ABOUT_DATA_SUCCESS",
  FETCHING_ABOUT_DATA_FAILURE: "FETCHING_ABOUT_DATA_FAILURE",
};

export default AboutPageType;
