/** @format */

const FeatureAction = {
  FETCHING_FEATURE_DATA_START: "FETCHING_FEATURE_DATA_START",
  FETCHING_FEATURE_DATA_SUCCESS: "FETCHING_FEATURE_DATA_SUCCESS",
  FETCHING_FEATURE_DATA_FAILURE: "FETCHING_FEATURE_DATA_FAILURE",
};

export default FeatureAction;
