/** @format */

const PostType = {
  FETCHING_POST_DATA_START: "FETCHING_POST_DATA_START",
  FETCHING_POST_DATA_SUCCESS: "FETCHING_POST_DATA_SUCCESS",
  FETCHING_POST_DATA_FAILURE: "FETCHING_POST_DATA_FAILURE",
};

export default PostType;
