/** @format */

const cartActionType = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ONSCROLL_CART_HIDDEN: "ONSCROLL_CART_HIDDEN",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  HOVER_CART_POPUP: "HOVER_CART_POPUP",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
  SET_INIT_CART: "SET_INIT_CART",
  CART_SHOULD_DESPLAY: "CART_SHOULD_DESPLAY",
};

export default cartActionType;
