[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[build]
 Functions="functions-build"
 command ="npm run build"