[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/*"
  to = "/"
  status = 200