/**
 * /*
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * author: ONESEC (https://sketchfab.com/ONESEC)
 * license: COPYRIGHT TO ONESEC
 * source: https://sketchfab.com/3d-models/menpo-black-red-c83ed5788ece4a9c9273ad30eb95bdcf
 * title: Menpo-Black red
 *
 * @format
 */

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function MenpoBlackModel({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/threeModel/Menpo/black/scene.gltf");
  return (
    <group
      dispose={null}
      rotation={[-Math.PI / 2, 0, 0]}
      position={[0, -2.5, 0]}
      scale={0.11}
      ref={group}
      {...props}
    >
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["1-8color128128128"]}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials["1-8color128128128"]}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["a-aGee3aRealogocolor128128128"]}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials["a-aGee3aRealogoptc-metallic-gold255255135"]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["a-aGee3aRealogoptc-painted-red25500"]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials["a-aGee3aRealogoptc-painted-yellow2552550"]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["a-aGee3aRealogoaPeptc-metallic-gold255255135"]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials["a-aGee3aRealogoaPecolor128128128"]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials["a-aGee3aRealogoaPeptc-painted-red25500"]}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials["a-aGee3aRealogoaPeptc-painted-yellow2552550"]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials["back1-2color128128128"]}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.glasscolor128128128}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials["glassptc-ceramic255255242"]}
      />
    </group>
  );
}

useGLTF.preload("/threeModel/Menpo/black/scene.gltf");
