/**
 * /*
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * author: ONESEC (https://sketchfab.com/ONESEC)
 * license: COPYRIGHT TO ONESEC
 * source: https://sketchfab.com/3d-models/mark-i-black-rose-8829b07615bf44eabb1e60d2740e4fcf
 * title: MARK I - Black Rose
 *
 * @format
 */

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function MarkIBlackModel({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/threeModel/MarkI/black/scene.gltf");
  return (
    <group
      dispose={null}
      rotation={[-Math.PI / 2, 0, 0]}
      position={[0, -2.5, 0]}
      scale={0.11}
      ref={group}
      {...props}
    >
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Anodized_Aluminum_Brushed_90X_Black}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.material_8}
        material-opacity={0.3}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Aluminum_Rough_1}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials["glass1-2color128128128"]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["glass1-2ptc-ceramic255255242"]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials["pbcptc-painted-green02550"]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Brass_Textured}
      />
      <mesh geometry={nodes.Object_9.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material} />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.Brass_Polished}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.Brass_Polished}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.Brass_Polished}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.Brass_Polished}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.Brass_Polished}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.Brass_Polished}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials.Brass_Polished}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.Brass_Polished}
      />
    </group>
  );
}

useGLTF.preload("/threeModel/MarkI/black/scene.gltf");
