/**
 * /*
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * author: ONESEC (https://sketchfab.com/ONESEC)
 * license: COPYRIGHT TO ONESEC
 * source: https://sketchfab.com/3d-models/aviator-black-8ee68f861a154fa291580718d2d8c00d
 * title: AVIATOR - Black
 *
 * @format
 */

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function AviatorBlackModel({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/threeModel/Aviator/black/scene.gltf");

  return (
    <group
      rotation={[-Math.PI / 2, 0, 0]}
      ref={group}
      {...props}
      dispose={null}
      scale={0.1}
    >
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Clear_Shiny_Plastic_Orange}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.Paint_Metallic_White}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Cylinder_Material}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.Clear_Textured_Plastic_Grey}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Aluminum_Brushed_90X_1}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.tailright3color128128128}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.tailright3color128128128_1}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.Brass_Brushed_90X}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.Paint_Textured_Green}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials["a-GeFcccolor128128128"]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials["a-GeFcccolor128128128"]}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.Cylinder_Material_1}
      />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Rubber} />
      receiveShadow castShadow
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.footleft2color128128128}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials["footleft2ptc-ceramic255255242"]}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials.footright3color128128128}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials["footright3ptc-ceramic255255242"]}
      />
      <mesh geometry={nodes.Object_19.geometry} material={materials.material} />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.Chrome_Brushed_90X_3}
      />
    </group>
  );
}

useGLTF.preload("/threeModel/Aviator/black/scene.gltf");
