/**
 * /*
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * author: Felix Yadomi (https://sketchfab.com/felixyadomi)
 * license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
 * source: https://sketchfab.com/3d-models/heart-shaped-glasses-97cbff16eec648fdb211ea58159bd9ba
 * title: Heart-shaped glasses
 *
 * @format
 */

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Glasses({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/threeModel/heart-shaped_glasses/scene.glb"
  );
  return (
    <group ref={group} {...props} dispose={null} scale={2}>
      <group position={[0, -0.04, 0.1]} rotation={[-1.54, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.35, -0.57, 0]}>
            <group position={[2.33, -0.88, -3.45]} rotation={[-0.24, 0, 0]}>
              <mesh
                geometry={nodes.Object_6.geometry}
                material={materials.earpiece}
              />
            </group>
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials["armature.001"]}
            />
            <group position={[2.33, -0.02, -0.17]} rotation={[-0.24, 0, 0]}>
              <mesh
                geometry={nodes.Object_10.geometry}
                material={materials.branch}
              />
            </group>
            <group position={[2.33, -0.29, -1.17]} rotation={[-0.24, 0, 0]}>
              <mesh
                geometry={nodes.Object_12.geometry}
                material={materials.branch}
              />
            </group>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.armature}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/threeModel/heart-shaped_glasses/scene.glb");
