/** @format */

const ShopPageActionType = {
  FETCHING_SHOPPAGE_START: "FETCHING_SHOPPAGE_START",
  FETCHING_SHOPPAGE_SUCCESS: "FETCHING_SHOPPAGE_SUCCESS",
  FETCHING_SHOPPAGE_FAILURE: "FETCHING_SHOPPAGE_FAILURE",
};

export default ShopPageActionType;
