/** @format */

const ActionUserType = {
  EXPRESS_SIGNIN_START: "EXPRESS_SIGNIN_START",
  EXPRESS_SIGNIN_SUCESS: "EXPRESS_SIGNIN_SUCESS",
  EXPRESS_SIGNIN_FAILURE: "EXPRESS_SIGNIN_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_START: "SIGN_OUT",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
};

export default ActionUserType;
