/** @format */

const ActionUserType = {
  EXPRESS_SIGNIN_START: "EXPRESS_SIGNIN_START",
  EXPRESS_SIGNIN_SUCCESS: "EXPRESS_SIGNIN_SUCCESS",
  CREATE_ACCOUNT_START: "CREATE_ACCOUNT_START",
  SIGN_IN_WITH_EMAIL_START: "SIGN_IN_WITH_EMAIL_START",

  SEND_CHANGE_PASSWORD_EMAIL: "SEND_CHANGE_PASSWORD_EMAIL",
  SING_IN_FAILURE: "SING_IN_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_START: "SIGN_OUT",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
};

export default ActionUserType;
